# This 3 stage ci pipeline is purpose-built for cdk in typescript
# it also includes support for python lambdas
# it implements a basic build, static check, and deploy process
# this pipeline can be removed if and when this repo moves to github

stages:          # List of stages for jobs, and their order of execution
  - build
  - static
  - validate
  - deploy

variables:
  PYTHON_SCRIPTS: bin/stats
  TS_SCRIPTS: bin/stats
  SHELL_SCRIPTS: bin/validate-config


build-job:       # Validates that cdk will build, install dependencies, and that cdk with synth
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo "installing node, npm, docker, aws-cli"
    - apk add --update nodejs npm
    - apk add --no-cache python3 py3-pip
    - apk add --update aws-cli
    - node --version
    - npm --version
    - python3 --version
    - pip3 --version
    - aws --version
    - echo "Logging into AWS Docker Public ECR to build lambda environment"
    - docker logout public.ecr.aws
    - echo "Installing typescript as dependency"
    - npm install typescript@latest -g
    - echo "succesfully installed typescript"
    - echo "Installing python as dependency"
    - echo "succesfully installed python"
    - echo "Installing all package dependencies"
    - npm install -g aws-cdk
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Synthesizing CDK..."
    - cdk synth
    - echo "CDK synth complete."

tslint-test-job:   # Runs eslint for typescript to validate linting of typescript code
  stage: static
  image: node:latest
  script:
    - echo "Installing typescript as dependency"
    - npm install typescript@latest -g
    - echo "succesfully installed typescript"
    - echo "Installing python as dependency"
    - npm i python@latest -g
    - echo "succesfully installed python"
    - echo "Installing all package dependencies"
    - npm install -g aws-cdk
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Linting code... This will take about 10 seconds."
    - npm run lint
    - echo "No lint issues found."

bandit:   # Runs python bandit test job for security checks on python code in repo
  stage: static    # Only starts when job in build stage completes successfully
  image:
    name: python:latest
    entrypoint:
      - "/usr/bin/env"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  script:
    - ls -la
    - python --version
    - pip3 install --upgrade pip
    - pip3 install --upgrade setuptools
    - pip3 install bandit
    - bandit ./ -r | tee ./output_test.log

cdk-nag-job:   # runs cdk-nag script in test stage
  stage: static
  image: node:latest
  script:
    - echo "Installing typescript as dependency"
    - npm install typescript@latest -g
    - echo "succesfully installed typescript"
    - echo "Installing python as dependency"
    - npm i python@latest -g
    - echo "succesfully installed python"
    - echo "Installing all package dependencies"
    - npm install -g aws-cdk
    - npm ci
    - echo "succesfully installed package dependencies!"
    - echo "Building with npm..."
    - npm run build
    - echo "Build complete."
    - echo "Running cdk nag to check for security vulnerabilities"
    - cdk synth --context nag=true
    - echo "Completed CDK nag check"

taskcat-deploy-job:      # Runs taskcat deployment job in test AWS account
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Simulating application deployment..."
    - echo "Application deployment placeholder passed"